"""Verified operator-task engine: an ask closes only when its check passes.

# arch: operator asks as observed facts - append-only hash-chained event log, verify-to-close

WHY (ingest directive P0-1, FLEET-COMMON item 1). Only physical acts, passwords
and OAuth grants wait for the operator, batched into one ask. Until this module
that ask was prose in the hand-off file: nothing recorded whether it was done,
nothing closed it, and the same ask could be raised twice. Here an ask is a TASK
keyed by (capability, subject):

  * a second request for an OPEN key JOINS the open task and notifies nobody;
  * every task carries a reason, human-followable steps, optional ordered
    handoffs (a settings pane, a page to open) and a VERIFY argv;
  * the operator pressing "done" only TRIGGERS the check - the task closes
    only when the check exits 0. Missing, crashing or timed-out = not done;
  * comments never close; withdraw closes with a reason and never re-notifies;
  * open/closed is DERIVED by folding the append-only event log - there is no
    stored state flag to drift from what happened;
  * the log is a hash chain (seq + prev + sha256 per line), so an edited or
    deleted past event is detected and every further write is refused;
  * `verify_pending()` re-runs every open check; it rides the inbox responder's
    5-minute `--once` tick (tools/lw_inbox_responder.py), not a new task.

THE HAND-OFF RENDERS FROM HERE. `tools/lw_next_session.py --write` replaces the
"Operator asks" block of LW-NEXT-SESSION.txt with `render_operator_asks()` over
the pending list, so the batched ask is always current and never hand-written.
This module is the source the hand-off renders from, not a second hand-off.

SAFETY. A verify argv is arbitrary code run unattended:
  * argv must be a non-empty list/tuple of str - a string is refused at the
    API boundary (no shell, ever: `shell=False`);
  * its executable must be on `ALLOWED_EXECUTABLES` (by basename) or be this
    interpreter;
  * only the owning tree (`OWNER`, LW) registers a check - a note from another
    tree never reaches `request()`; the CLI is the only registration path;
  * every run gets CREATE_NO_WINDOW and a timeout.

NOTIFICATIONS go through a pluggable sink whose `send(message)` returns
(ok, detail); the engine wraps it so a sink never raises into a caller. Default
`FileSink` (ops/runtime/operator_tasks/notifications.jsonl). `LW_OPS_TASKS_HOLD`
set to anything non-empty makes every send a no-op recorded as "held".

Runtime root: `ops/runtime/operator_tasks/` (gitignored), overridable through
`LW_OPS_TASKS_ROOT` - the suite points it at a per-test dir (tests/conftest.py).

CLI:
    python tools/lw_ops_tasks.py request --cap physical --subject dac \\
        --reason "..." --step "..." [--handoff "..."] --verify-json '["python","-c","..."]'
    python tools/lw_ops_tasks.py pending | list | render
    python tools/lw_ops_tasks.py done T0001          # exit 0 only if it closed
    python tools/lw_ops_tasks.py comment T0001 "text"
    python tools/lw_ops_tasks.py withdraw T0001 "reason"
    python tools/lw_ops_tasks.py verify-pending
Coverage: tests/test_lw_ops_tasks.py.
"""
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NO_WINDOW = getattr(subprocess, "CREATE_NO_WINDOW", 0)

ROOT_ENV = "LW_OPS_TASKS_ROOT"
HOLD_ENV = "LW_OPS_TASKS_HOLD"
OWNER = "LW"
VERIFY_TIMEOUT_S = 60.0

# By lower-cased basename. Interpreters and read-only probes this tree already
# runs; a shell (cmd, powershell, bash) is deliberately absent - a verify that
# needs one is a script file run by python.
ALLOWED_EXECUTABLES = frozenset({
    "python", "python.exe", "python3", "python3.exe", "pythonw.exe", "py.exe",
    "git", "git.exe", "gh", "gh.exe", "schtasks", "schtasks.exe",
    "where.exe", "reg.exe", "sc.exe",
})

ASKS_BEGIN = ("Operator asks (generated by tools/lw_ops_tasks.py from the open-task "
              "log; do not edit by hand):")
ASKS_END = "  (end operator asks)"

LOCK_WAIT_S = 10.0


class TaskRefused(ValueError):
    """A request the engine will not record (bad argv, foreign owner, ...)."""


class TamperedLog(RuntimeError):
    """The event log's hash chain does not hold: a past event was edited/lost."""


def default_root() -> Path:
    env = os.environ.get(ROOT_ENV, "").strip()
    return Path(env) if env else ROOT / "ops" / "runtime" / "operator_tasks"


def _now() -> str:
    return dt.datetime.now(dt.UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _digest(event: dict) -> str:
    body = {k: v for k, v in event.items() if k != "hash"}
    return hashlib.sha256(json.dumps(body, sort_keys=True).encode("utf-8")).hexdigest()


# Single-writer lock: lw_watch's pid-stamped lock dir (liveness by pid, never mtime)
try:
    from lw_watch import LockBusy, pid_alive, watch_lock as pid_lock  # noqa: F401
except ImportError:  # running with tools/ off sys.path
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from lw_watch import LockBusy, pid_alive, watch_lock as pid_lock  # noqa: F401


# ---------------------------------------------------------------------------
# Store
# ---------------------------------------------------------------------------

class JsonlTaskStore:
    """Append-only JSONL event log with a sha256 hash chain.

    Each line: {..., "seq": n, "prev": <hash of line n-1 or "">, "hash": ...}.
    `read()` verifies the whole chain and raises TamperedLog on any break;
    `append()` holds a single-writer lock and re-verifies before writing, so a
    tampered log is never extended.
    """

    def __init__(self, path: Path):
        self.path = Path(path)
        self.lock_dir = self.path.with_name(self.path.name + ".lock")

    def read(self) -> list[dict]:
        if not self.path.exists():
            return []
        events, prev = [], ""
        text = self.path.read_text(encoding="utf-8")
        for n, line in enumerate(text.splitlines(), 1):
            if not line.strip():
                continue
            try:
                ev = json.loads(line)
            except ValueError:
                raise TamperedLog(f"line {n} is not JSON") from None
            if not isinstance(ev, dict):
                raise TamperedLog(f"line {n} is not an object")
            if ev.get("seq") != len(events) + 1:
                raise TamperedLog(f"line {n}: sequence break (seq {ev.get('seq')!r})")
            if ev.get("prev") != prev:
                raise TamperedLog(f"line {n}: chain break (prev does not match)")
            if ev.get("hash") != _digest(ev):
                raise TamperedLog(f"line {n}: content does not match its hash")
            prev = ev["hash"]
            events.append(ev)
        return events

    def append(self, event: dict) -> dict:
        with pid_lock(self.lock_dir, wait_s=LOCK_WAIT_S):
            events = self.read()
            ev = dict(event)
            ev["seq"] = len(events) + 1
            ev["prev"] = events[-1]["hash"] if events else ""
            ev["hash"] = _digest(ev)
            self.path.parent.mkdir(parents=True, exist_ok=True)
            with self.path.open("a", encoding="utf-8", newline="\n") as fh:
                fh.write(json.dumps(ev, sort_keys=True) + "\n")
                fh.flush()
                os.fsync(fh.fileno())
            return ev


# ---------------------------------------------------------------------------
# Sinks
# ---------------------------------------------------------------------------

class FileSink:
    """Append each notification as one JSON line. Returns (ok, detail)."""

    def __init__(self, path: Path):
        self.path = Path(path)

    def send(self, message: dict):
        try:
            self.path.parent.mkdir(parents=True, exist_ok=True)
            with self.path.open("a", encoding="utf-8", newline="\n") as fh:
                fh.write(json.dumps({"ts": _now(), **message}, sort_keys=True) + "\n")
            return True, f"appended to {self.path.name}"
        except OSError as exc:
            return False, f"{type(exc).__name__}"


# ---------------------------------------------------------------------------
# Verify runner
# ---------------------------------------------------------------------------

def validate_argv(argv) -> list[str]:
    """The argv as a list of str, or TaskRefused. Never a string, never a shell."""
    # One test covers str and bytes: neither is a list/tuple.
    if not isinstance(argv, (list, tuple)) or not argv:
        raise TaskRefused("verify argv must be a non-empty list of arguments "
                          f"(got {type(argv).__name__}) - never a string")
    if not all(isinstance(a, str) and a != "" for a in argv):
        raise TaskRefused("every verify argument must be a non-empty string")
    exe = argv[0]
    same = os.path.normcase(os.path.abspath(exe)) == os.path.normcase(sys.executable)
    if not same and Path(exe).name.lower() not in ALLOWED_EXECUTABLES:
        raise TaskRefused(f"executable {Path(exe).name!r} is not on the allowlist")
    return list(argv)


def run_verify(argv, timeout_s: float = VERIFY_TIMEOUT_S) -> dict:
    """Run the check. {"passed", "rc", "error"}; never raises."""
    try:
        argv = validate_argv(argv)
    except TaskRefused as exc:
        return {"passed": False, "rc": None, "error": f"refused: {exc}"}
    try:
        r = subprocess.run(argv, shell=False, capture_output=True, timeout=timeout_s,
                           stdin=subprocess.DEVNULL, creationflags=NO_WINDOW)
    except subprocess.TimeoutExpired:
        return {"passed": False, "rc": None, "error": "timeout"}
    except OSError as exc:
        return {"passed": False, "rc": None, "error": f"{type(exc).__name__}"}
    err = ""
    if r.returncode != 0:
        tail = (r.stderr or b"").decode("utf-8", "replace").strip().splitlines()
        err = tail[-1][:200] if tail else f"exit {r.returncode}"
    return {"passed": r.returncode == 0, "rc": r.returncode, "error": err}


# ---------------------------------------------------------------------------
# Engine
# ---------------------------------------------------------------------------

@dataclass
class Task:
    id: str
    cap: str
    subject: str
    reason: str
    steps: list
    handoffs: list
    verify_argv: list
    owner: str
    opened: str
    state: str = "open"            # open | closed | withdrawn - derived, never stored
    comments: list = field(default_factory=list)
    attempts: int = 0
    last_error: str = ""


def fold(events: list[dict]) -> dict[str, Task]:
    """Derive every task's state from the event log."""
    tasks: dict[str, Task] = {}
    for ev in events:
        kind, tid = ev.get("kind"), ev.get("task")
        if kind == "request":
            tasks[tid] = Task(tid, ev["cap"], ev["subject"], ev["reason"], list(ev["steps"]),
                              list(ev.get("handoffs") or []), list(ev["verify_argv"]),
                              ev["owner"], ev["ts"])
            continue
        t = tasks.get(tid)
        if t is None:
            continue
        if kind == "comment":
            t.comments.append(ev.get("text", ""))
        elif kind == "verify":
            t.attempts += 1
            t.last_error = "" if ev.get("passed") else str(ev.get("error") or "")
        elif kind == "close" and t.state == "open":
            t.state = "closed"
        elif kind == "withdraw" and t.state == "open":
            t.state = "withdrawn"
    return tasks


class TaskEngine:
    def __init__(self, store: JsonlTaskStore, sink=None, *,
                 verify_timeout_s: float = VERIFY_TIMEOUT_S, runner=run_verify):
        self.store = store
        self.sink = sink if sink is not None else FileSink(store.path.with_name(
            "notifications.jsonl"))
        self.verify_timeout_s = verify_timeout_s
        self.runner = runner

    # -- reads --------------------------------------------------------------
    def tasks(self) -> dict[str, Task]:
        return fold(self.store.read())

    def task(self, tid: str) -> Task:
        t = self.tasks().get(tid)
        if t is None:
            raise KeyError(tid)
        return t

    def pending(self) -> list[Task]:
        return [t for t in self.tasks().values() if t.state == "open"]

    # -- writes -------------------------------------------------------------
    def _event(self, kind: str, tid: str, **fields) -> dict:
        return self.store.append({"kind": kind, "task": tid, "ts": _now(), **fields})

    def request(self, cap: str, subject: str, reason: str, steps, verify_argv,
                handoffs=None, owner: str = OWNER) -> str:
        if owner != OWNER:
            raise TaskRefused(f"owner {owner!r} may not register a check in {OWNER}")
        argv = validate_argv(verify_argv)
        for name, val in (("cap", cap), ("subject", subject), ("reason", reason)):
            if not isinstance(val, str) or not val.strip():
                raise TaskRefused(f"{name} must be a non-empty string")
        steps = [str(s) for s in (steps or [])]
        if not steps:
            raise TaskRefused("a task needs at least one human-followable step")
        events = self.store.read()
        for t in fold(events).values():
            if t.state == "open" and (t.cap, t.subject) == (cap, subject):
                self._event("join", t.id, reason=reason)
                return t.id
        tid = f"T{1 + sum(1 for e in events if e.get('kind') == 'request'):04d}"
        self._event("request", tid, cap=cap, subject=subject, reason=reason, steps=steps,
                    handoffs=[str(h) for h in (handoffs or [])], verify_argv=argv,
                    owner=owner)
        self._notify(tid, {"task": tid, "cap": cap, "subject": subject, "reason": reason})
        return tid

    def _notify(self, tid: str, message: dict) -> None:
        if os.environ.get(HOLD_ENV, "").strip():
            ok, detail = False, "held"
        else:
            try:
                ok, detail = self.sink.send(message)
                ok, detail = bool(ok), str(detail)
            except Exception as exc:  # noqa: BLE001 - a sink never raises into us
                ok, detail = False, f"sink raised {type(exc).__name__}"
        self._event("notify", tid, ok=ok, detail=detail)

    def comment(self, tid: str, text: str) -> None:
        self.task(tid)
        self._event("comment", tid, text=str(text))

    def withdraw(self, tid: str, reason: str) -> None:
        t = self.task(tid)
        if t.state == "open":
            self._event("withdraw", tid, reason=str(reason))

    def _check(self, t: Task, trigger: str) -> bool:
        res = self.runner(t.verify_argv, timeout_s=self.verify_timeout_s)
        self._event("verify", t.id, trigger=trigger, passed=bool(res.get("passed")),
                    rc=res.get("rc"), error=str(res.get("error") or ""))
        if res.get("passed"):
            self._event("close", t.id, by=trigger)
            return True
        return False

    def done(self, tid: str) -> dict:
        """The operator says done: run the check; close only on exit 0."""
        t = self.task(tid)
        if t.state != "open":
            return {"task": tid, "closed": t.state == "closed", "state": t.state}
        closed = self._check(t, "done")
        return {"task": tid, "closed": closed, "state": "closed" if closed else "open"}

    def verify_pending(self) -> dict:
        """Re-run every open check (the scheduled pass)."""
        out = {"checked": [], "closed": [], "open": []}
        for t in self.pending():
            out["checked"].append(t.id)
            (out["closed"] if self._check(t, "scheduled") else out["open"]).append(t.id)
        return out


def default_engine(root: Path | None = None) -> TaskEngine:
    r = Path(root) if root is not None else default_root()
    return TaskEngine(JsonlTaskStore(r / "events.jsonl"), FileSink(r / "notifications.jsonl"))


# ---------------------------------------------------------------------------
# Hand-off rendering
# ---------------------------------------------------------------------------

def _gate(lines: list[str]) -> list[str]:
    try:
        from precommit_gate import scan_handoff_text
    except ImportError:
        sys.path.insert(0, str(Path(__file__).resolve().parent))
        from precommit_gate import scan_handoff_text
    return scan_handoff_text("\n".join(lines))


def render_operator_asks(tasks: list[Task]) -> str:
    """The hand-off's "Operator asks" block, from the pending task list.

    The verify argv is never rendered (it may carry a path). A task whose own
    text would fail the hand-off content gate is listed by id only.
    """
    out = [ASKS_BEGIN]
    if not tasks:
        out.append("  none open")
    for t in tasks:
        lines = [f"  - {t.id} {t.cap}/{t.subject}: {t.reason}",
                 "      steps: " + "; ".join(f"{i}) {s}" for i, s in enumerate(t.steps, 1))]
        if t.handoffs:
            lines.append("      open first: " + " -> ".join(t.handoffs))
        if t.last_error:
            lines.append(f"      last check: not done ({t.attempts} tries)")
        if _gate(lines):
            lines = [f"  - {t.id} {t.cap}: text withheld (fails the hand-off gate); "
                     f"see python tools/lw_ops_tasks.py pending"]
        out.extend(lines)
        out.append(f"      close: python tools/lw_ops_tasks.py done {t.id} "
                   "(closes only when its check passes)")
    out.append(ASKS_END)
    return "\n".join(out) + "\n"


def inject_operator_asks(text: str, engine: TaskEngine | None = None) -> str:
    """Replace (or append) the generated block. Never raises."""
    eng = engine if engine is not None else default_engine()
    try:
        block = render_operator_asks(eng.pending())
    except Exception as exc:  # noqa: BLE001 - /done must never fail on this
        block = (f"{ASKS_BEGIN}\n  UNKNOWN - task log unreadable "
                 f"({type(exc).__name__}); run python tools/lw_ops_tasks.py pending\n"
                 f"{ASKS_END}\n")
    lines = text.splitlines(keepends=True)
    kept, skipping = [], False
    for line in lines:
        bare = line.rstrip("\r\n")
        if bare == ASKS_BEGIN:
            skipping = True
            continue
        if skipping:
            if bare == ASKS_END:
                skipping = False
            continue
        kept.append(line)
    body = "".join(kept)
    if body and not body.endswith("\n"):
        body += "\n"
    return body + block


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _task_json(t: Task) -> dict:
    return {"id": t.id, "cap": t.cap, "subject": t.subject, "reason": t.reason,
            "steps": t.steps, "handoffs": t.handoffs, "state": t.state,
            "attempts": t.attempts, "last_error": t.last_error, "opened": t.opened}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--root", type=Path, default=None)
    sub = ap.add_subparsers(dest="cmd", required=True)
    r = sub.add_parser("request")
    r.add_argument("--cap", required=True)
    r.add_argument("--subject", required=True)
    r.add_argument("--reason", required=True)
    r.add_argument("--step", action="append", default=[])
    r.add_argument("--handoff", action="append", default=[])
    r.add_argument("--verify-json", required=True, help="the verify argv as a JSON list")
    sub.add_parser("pending")
    sub.add_parser("list")
    sub.add_parser("render")
    sub.add_parser("verify-pending")
    d = sub.add_parser("done")
    d.add_argument("id")
    c = sub.add_parser("comment")
    c.add_argument("id")
    c.add_argument("text")
    w = sub.add_parser("withdraw")
    w.add_argument("id")
    w.add_argument("reason")
    args = ap.parse_args(argv)
    eng = default_engine(args.root)
    try:
        if args.cmd == "request":
            tid = eng.request(args.cap, args.subject, args.reason, args.step,
                              json.loads(args.verify_json), handoffs=args.handoff)
            print(json.dumps({"id": tid}))
            return 0
        if args.cmd in ("pending", "list"):
            ts = eng.pending() if args.cmd == "pending" else list(eng.tasks().values())
            print(json.dumps([_task_json(t) for t in ts], indent=2))
            return 0
        if args.cmd == "render":
            sys.stdout.write(render_operator_asks(eng.pending()))
            return 0
        if args.cmd == "verify-pending":
            print(json.dumps(eng.verify_pending()))
            return 0
        if args.cmd == "done":
            res = eng.done(args.id)
            print(json.dumps(res))
            return 0 if res["closed"] else 1
        if args.cmd == "comment":
            eng.comment(args.id, args.text)
            return 0
        if args.cmd == "withdraw":
            eng.withdraw(args.id, args.reason)
            return 0
    except (TaskRefused, TamperedLog, KeyError, ValueError, LockBusy) as exc:
        print(f"refused: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 2
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
